### ISSUE TITLE
data type of "page" is string in JSON

### ISSUE THREAD

**Issue by M-ZubairAhmed** [vinaypuppal/linklet-api#1]
Please convert datatype of page back to int currently it is under double quotations which my app is treating as string. Also to convert back to int i have to do again costly wrapping from string to int.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed Hey its `int` only, not `String`. See this screenshot

![screen shot 2017-04-24 at 11 36 10 pm](https://cloud.githubusercontent.com/assets/8843216/25351661/f709651e-2946-11e7-88a1-4eee0487454d.png)

**Comment by M-ZubairAhmed** [comment]
It is string itself
![photo](https://cloud.githubusercontent.com/assets/17708702/25378060/e0cda9ce-29c6-11e7-8ee9-fa926ddd4f3f.jpg)

**Comment by vinaypuppal** [comment]
Oh okay I will fix this tonight

**Comment by vinaypuppal** [comment]
Fixed it  🎉 
![screen shot 2017-04-25 at 10 45 35 pm](https://cloud.githubusercontent.com/assets/8843216/25398261/f5c14ec0-2a08-11e7-883b-c819cd929cf0.png)
